version: "3.5"
services:
  build:
   image: klakegg/hugo:latest
   volumes:
     - ./config.toml:/src/config.toml
     - ./content:/src/content
     - ./resources:/src/resources
     - ./static:/src/static
     - ./themes:/src/themes

  server:
    image: klakegg/hugo:latest
    command: server
    volumes:
      - ./config.toml:/src/config.toml
      - ./content:/src/content
      - ./resources:/src/resources
      - ./static:/src/static
      - ./themes:/src/themes
    ports:
      - 1313:1313
